apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbt-ksa
  namespace: data-pipeline
  annotations:
    iam.gke.io/gcp-service-account: novapay-data-pipeline@datadog-ese-sandbox.iam.gserviceaccount.com
  labels:
    app: dbt-pricing
