apiVersion: v1
kind: ServiceAccount
metadata:
  name: bq-sink-ksa
  namespace: data-pipeline
  annotations:
    # Workload Identity: maps this KSA to the GCP service account
    iam.gke.io/gcp-service-account: novapay-data-pipeline@datadog-ese-sandbox.iam.gserviceaccount.com
  labels:
    app: bq-sink
